### ISSUE TITLE
Select & backspace removes only the single character preceding the selection start

### ISSUE THREAD

**Issue by ErisDS** [bustlelabs/content-kit-editor#37] opened 2015-08-05 19:08 UTC
Using select + `backspace` has stopped working between 0.2.1 and 0.2.2

How I reproduced:

- on master (58ffbc8) using `broccoli serve` to test the demo

Test 1:
- select the second line and press `backspace`
- the newline between the first and second line is deleted, rather than the selected text

Test 2:
- select both lines and press `backspace`
- nothing is removed, the cursor moves to the beginning of the first line

Test 3:
- select a few characters in the middle of a word and press `backspace`
- the single character preceding the start of the selection is deleted

Placing the cursor between two characters and pressing `backspace` works as expected, deleting the single character preceding the cursor.

**Comment by bantic** [comment] 2015-08-05 20:46
Thanks for the super thorough report! We are moving toward semantic actions in post-0.2.1 versions (so, starting at 0.2.2) — moving from reacting to changes to the `contenteditable` surface towards capturing keystrokes and modifying the internal representation based on user intent. Deletion-handling code is not yet selection-aware, which I think is the root cause of all these failures. I'm starting work on this today.

**Closed** 2015-08-09 23:20 UTC
